name: CI

on: [push, pull_request]

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        otp: [29]
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v6

    - uses: awalsh128/cache-apt-pkgs-action@master
      with:
        packages: libpam0g-dev libyaml-dev
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - run: ./configure
    - run: rebar3 compile
    - run: rebar3 xref
    - run: rebar3 dialyzer
    - run: rebar3 eunit -v
